<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class AccountsBankNamesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        $time = Carbon::now();
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('accounts_bank_names')->truncate();
        DB::table('accounts_bank_names')->insert(array (
            0 =>
            array (
                'id' => 1,
                'accounts_bank_names' => 'Agrani Bank',
                'accounts_bank_codes' => 'Agrani Bank',
                'accounts_bank_address' => 'Agrani Bank address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            1 =>
            array (
                'id' => 2,
                'accounts_bank_names' => 'Janata Bank',
                'accounts_bank_codes' => 'Janata Bank',
                'accounts_bank_address' => 'Janata Bank address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            2 =>
            array (
                'id' => 3,
                'accounts_bank_names' => 'Rupali Bank',
                'accounts_bank_codes' => 'Rupali Bank',
                'accounts_bank_address' => 'Rupali Bank address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            3 =>
            array (
                'id' => 4,
                'accounts_bank_names' => 'Sonali Bank',
                'accounts_bank_codes' => 'Sonali Bank',
                'accounts_bank_address' => 'Sonali Bank address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            4 =>
            array (
                'id' => 5,
                'accounts_bank_names' => 'BASIC Bank',
                'accounts_bank_codes' => 'BASIC Bank',
                'accounts_bank_address' => 'BASIC Bank address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            5 =>
            array (
                'id' => 6,
                'accounts_bank_names' => 'BDBL',
                'accounts_bank_codes' => 'BDBL',
                'accounts_bank_address' => 'BDBL address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            6 =>
            array (
                'id' => 7,
                'accounts_bank_names' => 'Bangladesh Krishi Bank',
                'accounts_bank_codes' => 'Bangladesh Krishi Bank',
                'accounts_bank_address' => 'Bangladesh Krishi Bank address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            7 =>
            array (
                'id' => 8,
                'accounts_bank_names' => 'RAKUB.',
                'accounts_bank_codes' => 'RAKUB.',
                'accounts_bank_address' => 'RAKUB. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            8 =>
            array (
                'id' => 9,
                'accounts_bank_names' => 'AB Bank Ltd.',
                'accounts_bank_codes' => 'AB Bank Ltd.',
                'accounts_bank_address' => 'AB Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            9 =>
            array (
                'id' => 10,
                'accounts_bank_names' => 'Al-Arafah Islami Bank Ltd.',
                'accounts_bank_codes' => 'Al-Arafah Islami Bank Ltd.',
                'accounts_bank_address' => 'Al-Arafah Islami Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            10 =>
            array (
                'id' => 11,
                'accounts_bank_names' => 'Bangladesh Commerce Bank Ltd.',
                'accounts_bank_codes' => 'Bangladesh Commerce Bank Ltd.',
                'accounts_bank_address' => 'Bangladesh Commerce Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            11 =>
            array (
                'id' => 12,
                'accounts_bank_names' => 'Bank Asia Ltd.',
                'accounts_bank_codes' => 'Bank Asia Ltd.',
                'accounts_bank_address' => 'Bank Asia Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            12 =>
            array (
                'id' => 13,
                'accounts_bank_names' => 'BRAC Bank Ltd.',
                'accounts_bank_codes' => 'BRAC Bank Ltd.',
                'accounts_bank_address' => 'BRAC Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            13 =>
            array (
                'id' => 14,
                'accounts_bank_names' => 'Dhaka Bank Ltd.',
                'accounts_bank_codes' => 'Dhaka Bank Ltd.',
                'accounts_bank_address' => 'Dhaka Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            14 =>
            array (
                'id' => 15,
                'accounts_bank_names' => 'Dutch Bangla Bank Ltd.',
                'accounts_bank_codes' => 'Dutch Bangla Bank Ltd.',
                'accounts_bank_address' => 'Dutch Bangla Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            15 =>
            array (
                'id' => 16,
                'accounts_bank_names' => 'Eastern Bank Ltd.',
                'accounts_bank_codes' => 'Eastern Bank Ltd.',
                'accounts_bank_address' => 'Eastern Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            16 =>
            array (
                'id' => 17,
                'accounts_bank_names' => 'EXIM Bank Ltd.',
                'accounts_bank_codes' => 'EXIM Bank Ltd.',
                'accounts_bank_address' => 'EXIM Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            17 =>
            array (
                'id' => 18,
                'accounts_bank_names' => 'First Security Islami Bank Ltd.',
                'accounts_bank_codes' => 'First Security Islami Bank Ltd.',
                'accounts_bank_address' => 'First Security Islami Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            18 =>
            array (
                'id' => 19,
                'accounts_bank_names' => 'ICB Islamic Bank',
                'accounts_bank_codes' => 'ICB Islamic Bank',
                'accounts_bank_address' => 'ICB Islamic Bank address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            19 =>
            array (
                'id' => 20,
                'accounts_bank_names' => 'IFIC Bank Ltd.',
                'accounts_bank_codes' => 'IFIC Bank Ltd.',
                'accounts_bank_address' => 'IFIC Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            20 =>
            array (
                'id' => 21,
                'accounts_bank_names' => 'Islami Bank Bangladesh Ltd.',
                'accounts_bank_codes' => 'Islami Bank Bangladesh Ltd.',
                'accounts_bank_address' => 'Islami Bank Bangladesh Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            21 =>
            array (
                'id' => 22,
                'accounts_bank_names' => 'Jamuna Bank Ltd.',
                'accounts_bank_codes' => 'Jamuna Bank Ltd.',
                'accounts_bank_address' => 'Jamuna Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            22 =>
            array (
                'id' => 23,
                'accounts_bank_names' => 'Meghna Bank Ltd.',
                'accounts_bank_codes' => 'Meghna Bank Ltd.',
                'accounts_bank_address' => 'Meghna Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            23 =>
            array (
                'id' => 24,
                'accounts_bank_names' => 'Mercantile Bank Ltd.',
                'accounts_bank_codes' => 'Mercantile Bank Ltd.',
                'accounts_bank_address' => 'Mercantile Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            24 =>
            array (
                'id' => 25,
                'accounts_bank_names' => 'Midland Bank Ltd.',
                'accounts_bank_codes' => 'Midland Bank Ltd.',
                'accounts_bank_address' => 'Midland Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            25 =>
            array (
                'id' => 26,
                'accounts_bank_names' => 'Modhumoti Bank Ltd',
                'accounts_bank_codes' => 'Modhumoti Bank Ltd',
                'accounts_bank_address' => 'Modhumoti Bank Ltd address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            26 =>
            array (
                'id' => 27,
                'accounts_bank_names' => 'Mutual Trust Bank Ltd.',
                'accounts_bank_codes' => 'Mutual Trust Bank Ltd.',
                'accounts_bank_address' => 'Mutual Trust Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            27 =>
            array (
                'id' => 28,
                'accounts_bank_names' => 'National Bank Ltd.',
                'accounts_bank_codes' => 'National Bank Ltd.',
                'accounts_bank_address' => 'National Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            28 =>
            array (
                'id' => 29,
                'accounts_bank_names' => 'NCC Bank Ltd.',
                'accounts_bank_codes' => 'NCC Bank Ltd.',
                'accounts_bank_address' => 'NCC Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            29 =>
            array (
                'id' => 30,
                'accounts_bank_names' => 'NRB Bank Ltd.',
                'accounts_bank_codes' => 'NRB Bank Ltd.',
                'accounts_bank_address' => 'NRB Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            30 =>
            array (
                'id' => 31,
                'accounts_bank_names' => 'NRB Commercial Bank Ltd.',
                'accounts_bank_codes' => 'NRB Commercial Bank Ltd.',
                'accounts_bank_address' => 'NRB Commercial Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            31 =>
            array (
                'id' => 32,
                'accounts_bank_names' => 'NRB Global Bank Ltd.',
                'accounts_bank_codes' => 'NRB Global Bank Ltd.',
                'accounts_bank_address' => 'NRB Global Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            32 =>
            array (
                'id' => 33,
                'accounts_bank_names' => 'One Bank Ltd.',
                'accounts_bank_codes' => 'One Bank Ltd.',
                'accounts_bank_address' => 'One Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            33 =>
            array (
                'id' => 34,
                'accounts_bank_names' => 'Premier Bank Ltd.',
                'accounts_bank_codes' => 'Premier Bank Ltd.',
                'accounts_bank_address' => 'Premier Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            34 =>
            array (
                'id' => 35,
                'accounts_bank_names' => 'Prime Bank Ltd.',
                'accounts_bank_codes' => 'Prime Bank Ltd.',
                'accounts_bank_address' => 'Prime Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            35 =>
            array (
                'id' => 36,
                'accounts_bank_names' => 'Pubali Bank Ltd.',
                'accounts_bank_codes' => 'Pubali Bank Ltd.',
                'accounts_bank_address' => 'Pubali Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            36 =>
            array (
                'id' => 37,
                'accounts_bank_names' => 'Shahjalal Islami Bank Ltd.',
                'accounts_bank_codes' => 'Shahjalal Islami Bank Ltd.',
                'accounts_bank_address' => 'Shahjalal Islami Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            37 =>
            array (
                'id' => 38,
                'accounts_bank_names' => 'Shimanto Bank Ltd.',
                'accounts_bank_codes' => 'Shimanto Bank Ltd.',
                'accounts_bank_address' => 'Shimanto Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            38 =>
            array (
                'id' => 39,
                'accounts_bank_names' => 'Social Islami Bank Ltd.',
                'accounts_bank_codes' => 'Social Islami Bank Ltd.',
                'accounts_bank_address' => 'Social Islami Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            39 =>
            array (
                'id' => 40,
                'accounts_bank_names' => 'SBAC Bank Ltd.',
                'accounts_bank_codes' => 'SBAC Bank Ltd.',
                'accounts_bank_address' => 'SBAC Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            40 =>
            array (
                'id' => 41,
                'accounts_bank_names' => 'Southeast Bank Ltd.',
                'accounts_bank_codes' => 'Southeast Bank Ltd.',
                'accounts_bank_address' => 'Southeast Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            41 =>
            array (
                'id' => 42,
                'accounts_bank_names' => 'Standard Bank Ltd.',
                'accounts_bank_codes' => 'Standard Bank Ltd.',
                'accounts_bank_address' => 'Standard Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            42 =>
            array (
                'id' => 43,
                'accounts_bank_names' => 'The City Bank Ltd.',
                'accounts_bank_codes' => 'The City Bank Ltd.',
                'accounts_bank_address' => 'The City Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            43 =>
            array (
                'id' => 44,
                'accounts_bank_names' => 'The Farmers Bank Ltd.',
                'accounts_bank_codes' => 'The Farmers Bank Ltd.',
                'accounts_bank_address' => 'The Farmers Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            44 =>
            array (
                'id' => 45,
                'accounts_bank_names' => 'Trust Bank Ltd.',
                'accounts_bank_codes' => 'Trust Bank Ltd.',
                'accounts_bank_address' => 'Trust Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            45 =>
            array (
                'id' => 46,
                'accounts_bank_names' => 'Union Bank Ltd.',
                'accounts_bank_codes' => 'Union Bank Ltd.',
                'accounts_bank_address' => 'Union Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            46 =>
            array (
                'id' => 47,
                'accounts_bank_names' => 'United Commercial Bank Ltd.',
                'accounts_bank_codes' => 'United Commercial Bank Ltd.',
                'accounts_bank_address' => 'United Commercial Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            47 =>
            array (
                'id' => 48,
                'accounts_bank_names' => 'Uttara Bank Ltd.',
                'accounts_bank_codes' => 'Uttara Bank Ltd.',
                'accounts_bank_address' => 'Uttara Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            48 =>
            array (
                'id' => 49,
                'accounts_bank_names' => 'Bank Al-Falah',
                'accounts_bank_codes' => 'Bank Al-Falah',
                'accounts_bank_address' => 'Bank Al-Falah address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            49 =>
            array (
                'id' => 50,
                'accounts_bank_names' => 'CITI Bank NA',
                'accounts_bank_codes' => 'CITI Bank NA',
                'accounts_bank_address' => 'CITI Bank NA address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            50 =>
            array (
                'id' => 51,
                'accounts_bank_names' => 'Commercial Bank of Ceylon',
                'accounts_bank_codes' => 'Commercial Bank of Ceylon',
                'accounts_bank_address' => 'Commercial Bank of Ceylon address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            51 =>
            array (
                'id' => 52,
                'accounts_bank_names' => 'Habib Bank Ltd.',
                'accounts_bank_codes' => 'Habib Bank Ltd.',
                'accounts_bank_address' => 'Habib Bank Ltd. address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            52 =>
            array (
                'id' => 53,
                'accounts_bank_names' => 'HSBC',
                'accounts_bank_codes' => 'HSBC',
                'accounts_bank_address' => 'HSBC address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            53 =>
            array (
                'id' => 54,
                'accounts_bank_names' => 'National Bank of Pakistan',
                'accounts_bank_codes' => 'National Bank of Pakistan',
                'accounts_bank_address' => 'National Bank of Pakistan address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            54 =>
            array (
                'id' => 55,
                'accounts_bank_names' => 'Standard Chartered Bank',
                'accounts_bank_codes' => 'Standard Chartered Bank',
                'accounts_bank_address' => 'Standard Chartered Bank address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            55 =>
            array (
                'id' => 56,
                'accounts_bank_names' => 'State Bank of India',
                'accounts_bank_codes' => 'State Bank of India',
                'accounts_bank_address' => 'State Bank of India address',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
            56 =>
            array (
                'id' => 57,
                'accounts_bank_names' => 'Woori Bank Ltd.',
                'accounts_bank_codes' => 'Woori Bank Ltd.',
                'accounts_bank_address' => 'Woori Bank Ltd.',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => $time,
                'updated_at' => $time,
            ),
        ));
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

    }
}
