<?php

use Illuminate\Database\Seeder;

class AccountsSubCode2sTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        \DB::table('accounts_sub_code2s')->truncate();
        
        \DB::table('accounts_sub_code2s')->insert(array (
            0 => 
            array (
                'id' => 1,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Land',
                'sub_code2' => 3101,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:07:53',
                'updated_at' => '2019-05-15 12:07:53',
            ),
            1 => 
            array (
                'id' => 2,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Building',
                'sub_code2' => 3102,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:09:30',
                'updated_at' => '2019-05-15 12:09:30',
            ),
            2 => 
            array (
                'id' => 3,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Plant & Machinaries',
                'sub_code2' => 3103,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:10:29',
                'updated_at' => '2019-05-15 12:10:29',
            ),
            3 => 
            array (
                'id' => 4,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Office Equipment',
                'sub_code2' => 3104,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:10:58',
                'updated_at' => '2019-05-15 12:10:58',
            ),
            4 => 
            array (
                'id' => 5,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Motor Vehicles',
                'sub_code2' => 3105,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:11:39',
                'updated_at' => '2019-05-15 12:11:39',
            ),
            5 => 
            array (
                'id' => 6,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Laboratory Equipment',
                'sub_code2' => 3106,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:12:17',
                'updated_at' => '2019-05-15 12:12:17',
            ),
            6 => 
            array (
                'id' => 7,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Telephone & Mobile',
                'sub_code2' => 3107,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:12:41',
                'updated_at' => '2019-05-15 12:12:41',
            ),
            7 => 
            array (
                'id' => 8,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Factory Renovation',
                'sub_code2' => 3108,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:13:07',
                'updated_at' => '2019-05-15 12:13:07',
            ),
            8 => 
            array (
                'id' => 9,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Electrical Installation',
                'sub_code2' => 3109,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:13:29',
                'updated_at' => '2019-05-15 12:13:29',
            ),
            9 => 
            array (
                'id' => 10,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Computer & Accessories',
                'sub_code2' => 3110,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:14:00',
                'updated_at' => '2019-05-15 12:14:00',
            ),
            10 => 
            array (
                'id' => 11,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Tools & Equipment',
                'sub_code2' => 3111,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:14:23',
                'updated_at' => '2019-05-15 12:14:23',
            ),
            11 => 
            array (
                'id' => 12,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'Spare Parts',
                'sub_code2' => 3112,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:14:41',
                'updated_at' => '2019-05-15 12:14:41',
            ),
            12 => 
            array (
                'id' => 13,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'GENERATOR',
                'sub_code2' => 3113,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:14:59',
                'updated_at' => '2019-05-15 12:14:59',
            ),
            13 => 
            array (
                'id' => 14,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'GAS INSTALLATION',
                'sub_code2' => 3114,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:15:37',
                'updated_at' => '2019-05-15 12:15:37',
            ),
            14 => 
            array (
                'id' => 15,
                'main_code_id' => NULL,
                'sub_code_id' => 1,
                'sub_code_title2' => 'BOILER MACHINE',
                'sub_code2' => 3115,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:16:00',
                'updated_at' => '2019-05-15 12:16:00',
            ),
            15 => 
            array (
                'id' => 16,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'Stock & Store Finished Goods',
                'sub_code2' => 3201,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:16:20',
                'updated_at' => '2019-05-15 12:16:20',
            ),
            16 => 
            array (
                'id' => 17,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'Work In Process',
                'sub_code2' => 3202,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:18:35',
                'updated_at' => '2019-05-15 12:18:35',
            ),
            17 => 
            array (
                'id' => 18,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'FDR',
                'sub_code2' => 3203,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:20:02',
                'updated_at' => '2019-05-15 12:20:02',
            ),
            18 => 
            array (
                'id' => 19,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'MIT Raw-Material',
                'sub_code2' => 3204,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:20:23',
                'updated_at' => '2019-05-15 12:20:23',
            ),
            19 => 
            array (
                'id' => 20,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'Bills Receivable',
                'sub_code2' => 3205,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:20:48',
                'updated_at' => '2019-05-15 12:20:48',
            ),
            20 => 
            array (
                'id' => 21,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'Advansed,Deposit & Payments',
                'sub_code2' => 3206,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:21:15',
                'updated_at' => '2019-05-15 12:21:15',
            ),
            21 => 
            array (
                'id' => 22,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'Cash At Bank',
                'sub_code2' => 3207,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:21:37',
                'updated_at' => '2019-05-15 12:21:37',
            ),
            22 => 
            array (
                'id' => 23,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'Cash In Hand',
                'sub_code2' => 3208,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:21:57',
                'updated_at' => '2019-05-15 12:21:57',
            ),
            23 => 
            array (
                'id' => 24,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'Stock & Stores- Raw/Pack/Consumable Items',
                'sub_code2' => 3209,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:22:18',
                'updated_at' => '2019-05-15 12:22:18',
            ),
            24 => 
            array (
                'id' => 25,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'Advance Others',
                'sub_code2' => 3210,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:22:37',
                'updated_at' => '2019-05-15 12:22:37',
            ),
            25 => 
            array (
                'id' => 26,
                'main_code_id' => NULL,
                'sub_code_id' => 3,
                'sub_code_title2' => 'Priliminery & Pre-Production Expenses',
                'sub_code2' => 3301,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:23:07',
                'updated_at' => '2019-05-15 12:23:07',
            ),
            26 => 
            array (
                'id' => 27,
                'main_code_id' => NULL,
                'sub_code_id' => 4,
                'sub_code_title2' => 'Diran Enterprise Ltd',
                'sub_code2' => 3401,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:23:28',
                'updated_at' => '2019-05-15 12:23:28',
            ),
            27 => 
            array (
                'id' => 28,
                'main_code_id' => NULL,
                'sub_code_id' => 4,
                'sub_code_title2' => 'Diran Pole Indsutry Ltd',
                'sub_code2' => 3402,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:24:45',
                'updated_at' => '2019-05-15 12:24:45',
            ),
            28 => 
            array (
                'id' => 29,
                'main_code_id' => NULL,
                'sub_code_id' => 4,
                'sub_code_title2' => 'SR Engineering',
                'sub_code2' => 3403,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:25:08',
                'updated_at' => '2019-05-15 12:25:08',
            ),
            29 => 
            array (
                'id' => 30,
                'main_code_id' => NULL,
                'sub_code_id' => 4,
                'sub_code_title2' => 'Golden Teak',
                'sub_code2' => 3404,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:25:28',
                'updated_at' => '2019-05-15 12:25:28',
            ),
            30 => 
            array (
                'id' => 31,
                'main_code_id' => NULL,
                'sub_code_id' => 5,
            'sub_code_title2' => 'ADVANCE VAT(DEPOSIT)',
                'sub_code2' => 3501,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:25:47',
                'updated_at' => '2019-05-15 12:25:47',
            ),
            31 => 
            array (
                'id' => 32,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'VAT Expenses',
                'sub_code2' => 2101,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:27:22',
                'updated_at' => '2019-05-15 12:27:22',
            ),
            32 => 
            array (
                'id' => 33,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'Administration Expenses- H O',
                'sub_code2' => 2102,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:28:45',
                'updated_at' => '2019-05-15 12:28:45',
            ),
            33 => 
            array (
                'id' => 34,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'Sales & Marketing Expenses',
                'sub_code2' => 2103,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:29:53',
                'updated_at' => '2019-05-15 12:29:53',
            ),
            34 => 
            array (
                'id' => 35,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'Accounts & Finance Expenses',
                'sub_code2' => 2104,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:30:18',
                'updated_at' => '2019-05-15 12:30:18',
            ),
            35 => 
            array (
                'id' => 36,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'EXPORT EXPENSES',
                'sub_code2' => 2105,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:30:44',
                'updated_at' => '2019-05-15 12:30:44',
            ),
            36 => 
            array (
                'id' => 37,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
            'sub_code_title2' => 'Bank Interest (MTB)',
                'sub_code2' => 2106,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:31:02',
                'updated_at' => '2019-05-15 12:31:02',
            ),
            37 => 
            array (
                'id' => 38,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'Factory Expenses',
                'sub_code2' => 2107,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:31:26',
                'updated_at' => '2019-05-15 12:31:26',
            ),
            38 => 
            array (
                'id' => 39,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'Factory Expenses -Suspenses',
                'sub_code2' => 2108,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:31:50',
                'updated_at' => '2019-05-15 12:31:50',
            ),
            39 => 
            array (
                'id' => 40,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'UNABSORBED LABOUR OVERHEAD',
                'sub_code2' => 2110,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:32:15',
                'updated_at' => '2019-05-15 12:32:15',
            ),
            40 => 
            array (
                'id' => 41,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'LATE DELIVERY CHARGE',
                'sub_code2' => 2111,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:32:32',
                'updated_at' => '2019-05-15 12:32:32',
            ),
            41 => 
            array (
                'id' => 42,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'REB WORKS EXPENSES.',
                'sub_code2' => 2112,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:32:53',
                'updated_at' => '2019-05-15 12:32:53',
            ),
            42 => 
            array (
                'id' => 43,
                'main_code_id' => NULL,
                'sub_code_id' => 7,
                'sub_code_title2' => 'COST OF GOODS SOLD',
                'sub_code2' => 2201,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:33:16',
                'updated_at' => '2019-05-15 12:33:16',
            ),
            43 => 
            array (
                'id' => 44,
                'main_code_id' => NULL,
                'sub_code_id' => 8,
                'sub_code_title2' => 'MOSQUE DONATION',
                'sub_code2' => 2301,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:33:37',
                'updated_at' => '2019-05-15 12:33:37',
            ),
            44 => 
            array (
                'id' => 45,
                'main_code_id' => NULL,
                'sub_code_id' => 9,
                'sub_code_title2' => 'SALES LOCAL',
                'sub_code2' => 1101,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:34:07',
                'updated_at' => '2019-05-15 12:34:07',
            ),
            45 => 
            array (
                'id' => 46,
                'main_code_id' => NULL,
                'sub_code_id' => 9,
                'sub_code_title2' => 'SALES IMPORT',
                'sub_code2' => 1102,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:34:36',
                'updated_at' => '2019-05-15 12:34:36',
            ),
            46 => 
            array (
                'id' => 47,
                'main_code_id' => NULL,
                'sub_code_id' => 10,
                'sub_code_title2' => 'SCRAP SALES',
                'sub_code2' => 1201,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:34:58',
                'updated_at' => '2019-05-15 12:34:58',
            ),
            47 => 
            array (
                'id' => 48,
                'main_code_id' => NULL,
                'sub_code_id' => 11,
                'sub_code_title2' => 'Others Income',
                'sub_code2' => 1301,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:35:20',
                'updated_at' => '2019-05-15 12:35:20',
            ),
            48 => 
            array (
                'id' => 49,
                'main_code_id' => NULL,
                'sub_code_id' => 12,
                'sub_code_title2' => 'Issued, Subscribed & Paid Up Capital',
                'sub_code2' => 4101,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:35:43',
                'updated_at' => '2019-05-15 12:35:43',
            ),
            49 => 
            array (
                'id' => 50,
                'main_code_id' => NULL,
                'sub_code_id' => 12,
                'sub_code_title2' => 'Reserved & Surplus',
                'sub_code2' => 4102,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:36:13',
                'updated_at' => '2019-05-15 12:36:13',
            ),
            50 => 
            array (
                'id' => 51,
                'main_code_id' => NULL,
                'sub_code_id' => 12,
                'sub_code_title2' => 'Retain Earnings',
                'sub_code2' => 4103,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:36:37',
                'updated_at' => '2019-05-15 12:36:37',
            ),
            51 => 
            array (
                'id' => 52,
                'main_code_id' => NULL,
                'sub_code_id' => 12,
                'sub_code_title2' => 'Loan From Director',
                'sub_code2' => 4104,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:38:01',
                'updated_at' => '2019-05-15 12:38:01',
            ),
            52 => 
            array (
                'id' => 53,
                'main_code_id' => NULL,
                'sub_code_id' => 13,
                'sub_code_title2' => 'Current Liabilities',
                'sub_code2' => 4201,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:38:28',
                'updated_at' => '2019-05-15 12:38:28',
            ),
            53 => 
            array (
                'id' => 54,
                'main_code_id' => NULL,
                'sub_code_id' => 13,
                'sub_code_title2' => 'Sundry Creditors',
                'sub_code2' => 4202,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:38:57',
                'updated_at' => '2019-05-15 12:38:57',
            ),
            54 => 
            array (
                'id' => 55,
                'main_code_id' => NULL,
                'sub_code_id' => 14,
                'sub_code_title2' => 'Bills Payable',
                'sub_code2' => 4301,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:39:59',
                'updated_at' => '2019-05-15 12:39:59',
            ),
            55 => 
            array (
                'id' => 56,
                'main_code_id' => NULL,
                'sub_code_id' => 15,
                'sub_code_title2' => 'Accumulated Depreciation',
                'sub_code2' => 4401,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:40:32',
                'updated_at' => '2019-05-15 12:40:32',
            ),
            56 => 
            array (
                'id' => 57,
                'main_code_id' => NULL,
                'sub_code_id' => 16,
            'sub_code_title2' => 'Cash Credit (Hypo)',
                'sub_code2' => 4501,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:40:55',
                'updated_at' => '2019-05-15 12:40:55',
            ),
            57 => 
            array (
                'id' => 58,
                'main_code_id' => NULL,
                'sub_code_id' => 16,
            'sub_code_title2' => 'LATR-(M T B)',
                'sub_code2' => 4502,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:41:22',
                'updated_at' => '2019-05-15 12:41:22',
            ),
            58 => 
            array (
                'id' => 59,
                'main_code_id' => NULL,
                'sub_code_id' => 16,
            'sub_code_title2' => 'LOAN (GENERAL- MTB)',
                'sub_code2' => 4503,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:41:52',
                'updated_at' => '2019-08-06 19:20:36',
            ),
            59 => 
            array (
                'id' => 60,
                'main_code_id' => NULL,
                'sub_code_id' => 16,
                'sub_code_title2' => 'TERM LOAN INDUSTRIAL NEW',
                'sub_code2' => 4504,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:42:15',
                'updated_at' => '2019-05-15 12:42:15',
            ),
            60 => 
            array (
                'id' => 61,
                'main_code_id' => NULL,
                'sub_code_id' => 16,
                'sub_code_title2' => 'LEASE FINANCE',
                'sub_code2' => 4505,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:42:36',
                'updated_at' => '2019-05-15 12:42:36',
            ),
            61 => 
            array (
                'id' => 62,
                'main_code_id' => NULL,
                'sub_code_id' => 17,
                'sub_code_title2' => 'Salary Suspense',
                'sub_code2' => 4601,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:43:01',
                'updated_at' => '2019-05-15 12:43:01',
            ),
            62 => 
            array (
                'id' => 63,
                'main_code_id' => NULL,
                'sub_code_id' => 17,
                'sub_code_title2' => 'General Suspense',
                'sub_code2' => 4602,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:43:35',
                'updated_at' => '2019-05-15 12:43:35',
            ),
            63 => 
            array (
                'id' => 64,
                'main_code_id' => NULL,
                'sub_code_id' => 17,
                'sub_code_title2' => 'Bonus Suspense',
                'sub_code2' => 4603,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:44:04',
                'updated_at' => '2019-05-15 12:44:04',
            ),
            64 => 
            array (
                'id' => 65,
                'main_code_id' => NULL,
                'sub_code_id' => 17,
                'sub_code_title2' => 'Gas Bill Suspenses',
                'sub_code2' => 4604,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:44:25',
                'updated_at' => '2019-05-15 12:44:25',
            ),
            65 => 
            array (
                'id' => 66,
                'main_code_id' => NULL,
                'sub_code_id' => 17,
                'sub_code_title2' => 'Electric Bill Suspenses',
                'sub_code2' => 4605,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:44:48',
                'updated_at' => '2019-05-15 12:44:48',
            ),
            66 => 
            array (
                'id' => 67,
                'main_code_id' => NULL,
                'sub_code_id' => 17,
                'sub_code_title2' => 'VAT Suspenses',
                'sub_code2' => 4606,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:45:08',
                'updated_at' => '2019-05-15 12:45:08',
            ),
            67 => 
            array (
                'id' => 68,
                'main_code_id' => NULL,
                'sub_code_id' => 17,
                'sub_code_title2' => 'SUSPENSE ACCOUNTS',
                'sub_code2' => 4607,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:45:34',
                'updated_at' => '2019-05-15 12:45:34',
            ),
            68 => 
            array (
                'id' => 69,
                'main_code_id' => NULL,
                'sub_code_id' => 18,
                'sub_code_title2' => 'PEOPLES CREDIT',
                'sub_code2' => 4701,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:45:58',
                'updated_at' => '2019-05-15 12:45:58',
            ),
            69 => 
            array (
                'id' => 70,
                'main_code_id' => NULL,
                'sub_code_id' => 19,
                'sub_code_title2' => 'SHORT TERM LOAN A/C.',
                'sub_code2' => 4801,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-05-15 12:46:19',
                'updated_at' => '2019-05-15 12:46:19',
            ),
            70 => 
            array (
                'id' => 71,
                'main_code_id' => NULL,
                'sub_code_id' => 13,
            'sub_code_title2' => 'A/C OF PROVIDENT FUND (Employee/Co Contribution)',
                'sub_code2' => 4203,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2019-08-06 15:21:44',
                'updated_at' => '2019-08-06 15:28:34',
            ),
            71 => 
            array (
                'id' => 72,
                'main_code_id' => NULL,
                'sub_code_id' => 16,
            'sub_code_title2' => 'LATR-(Modhumoti)',
                'sub_code2' => 4506,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-06 19:11:43',
                'updated_at' => '2019-08-06 19:11:43',
            ),
            72 => 
            array (
                'id' => 73,
                'main_code_id' => NULL,
                'sub_code_id' => 16,
            'sub_code_title2' => 'Modhumoti Bank (Mirpur Branch)',
                'sub_code2' => 4507,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-06 19:44:32',
                'updated_at' => '2019-08-06 19:44:32',
            ),
            73 => 
            array (
                'id' => 74,
                'main_code_id' => NULL,
                'sub_code_id' => 2,
                'sub_code_title2' => 'LC Margin',
                'sub_code2' => 3211,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-07 14:17:12',
                'updated_at' => '2019-08-07 14:17:12',
            ),
            74 => 
            array (
                'id' => 75,
                'main_code_id' => NULL,
                'sub_code_id' => 6,
                'sub_code_title2' => 'Bkash Expense',
                'sub_code2' => 2113,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-29 12:35:27',
                'updated_at' => '2019-08-29 12:35:27',
            ),
        ));
        
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}